### ISSUE TITLE
Rename - naisctl ?

### ISSUE THREAD

**Issue by ybelMekk** [nais/nais-cli#8]
nais-d is a unfortunate , as the former app app used the name naisd.

**Comment by Kyrremann** [comment]
Er det tenkt at denne skal brukes til andre nais-relaterte ting? Ellers syns jeg den burde hete noe med Aiven.

**Comment by mortenlj** [comment]
På sikt kan det hende dette er grunnlaget for et generellt nais-cli, så har nå renamet repo til `nais-cli`, og binary til `nais`.
